baseurl: 
title: Compsci Guru
subtitle: Content-centric blogging
author: CSGuru
simple_search: http://google.com/search
description: A problem solving approach to learning programming.
name: Compsci Guru
markdown: Kramdown
kramdown:  
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:short_year/:title
timezone: Europe/London
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Documents/compsciguru.github.io
